### ISSUE TITLE
How to get validation status of form?

### ISSUE THREAD

**Issue by dArignac** [Availity/availity-reactstrap-validation#100]
Hi there,

I want to disable the form submit button as long as the form is invalid.
Is there a way to do this?
Somehow one needs to get the current status of the validation of the form for this.

Thanks!

**Comment by TheSharpieOne** [comment]
You can't. Due to poor design (I probably should have created an HOC or allowed function as a child) it's very difficult to  get at the current state of the validation/form. While you can see the current state of validation, via AvForm ref, there isn't a mechanism to inform your component when that state changes.

**Comment by dArignac** [comment]
Alright, understood. Not a bummer, would just have been a "nice to have" thing.
Thanks for your work on the components, they really help a lot!
