### ISSUE TITLE
Select box not updating on first change.

### ISSUE THREAD

**Issue by darrenmerrett** [Availity/availity-reactstrap-validation#12]
I'm using Chrome. When I change a select box the value doesn't change. If I change it a second time the value changes.

The issue seems to be with triggering onInputHandler and onChangeHandler. 

onInputHandler sets the correct changed value, but then "this.context.FormCtrl.setTouched" triggers a setState. The render then causes the onChangeHandler to return the original value, hence no change to the UI. When I then click a second time onInputHandler doesn't need to trigger "this.context.FormCtrl.setTouched", so the UI changes as it should.

Not sure if you need both onInputHandler and onChangeHandler?

**Comment by TheSharpieOne** [comment]
onInput and onChange are the same event in react, both fired after every input, but IE does some interesting things around triggering the events making both of them needing to be used as it doesn't seem to fire the events. 
The events themselves should have the same data since they are trigger by the same action. 
I'll look more into this, but in the meantime, as a workaround, you can change the validationEvent to use which event works best for you.this can be done on the entire form by passing validationEvent prop to the form or to an individual input by passing the validationEvent prop to the input.
Can you provide a working example of this issue using something like webpackbin, jsfiddle, plunkr, or something like that? The examples I have (https://availity.github.io/availity-reactstrap-validation/components/checkboxes/) don't seems to have this issue.

**Comment by darrenmerrett** [comment]
I have just tried your examples https://availity.github.io/availity-reactstrap-validation/components/avform/ in Chrome/Firefox & Safari and they all have the same problem with select boxes. When you click on the select box it doesn't change the first time.

**Comment by TheSharpieOne** [comment]
For some reason when I originally read this issue my mind saw checkboxes instead of select box. May bad. I see what's happening now.

**Comment by TheSharpieOne** [comment]
I actually had this fixed locally a while ago but forgot to release it. It's released now and the docs have been updated to the latest version so you can see the affects of the changes there.

Fixed via e8707dc. Released in [1.3.3](https://github.com/Availity/availity-reactstrap-validation/releases/tag/v1.3.3)

**Comment by darrenmerrett** [comment]
Thanks, works perfectly.
