### ISSUE TITLE
Forcing horizontal orientation

### ISSUE THREAD

**Issue by Trancedified** [Availity/availity-reactstrap-validation#129]
Adding AvForm inside of a Row tag and using a AvField while wrapped in a Col tag is forcing my textboxes to be stacked vertically. 

**This is what I'm getting:**
TextBox1
TextBox2
TextBox3

**The desired output would be:**
TextBox1 TextBox2 TextBox3

Is there a prop I can set to force a horizontal orientation?

Thanks.

**Comment by GoPro16** [comment]
Check our the example in the docs [here|https://availity.github.io/availity-reactstrap-validation/components/avform/).

The `Street Address` input is inline with the `Suite Number`. AvForm contains a `div` tag so the `Row` only affects the first level children. You will have to add the Row tag inside the `AvForm` or pass the Row Component as a `tag` prop on `AvForm` like below:

```javascript
<AvForm tag={Row}>
```

**Comment by Trancedified** [comment]
> Check our the example in the docs [here](https://availity.github.io/availity-reactstrap-validation/components/avform/).
> 
> The `Street` input is inline with the `Suite`. AvForm contains a `div` tag so the `Row` only affects the first level children. You will have to add the Row tag inside the `AvForm`

**Comment by Trancedified** [comment]
@GoPro16: Thanks. I saw the Suite example. I'll give it a shot!

**Comment by TheSharpieOne** [comment]
Also, if you want to have the label be to the left of the input (instead of above), there is a `grid` prop. It accepts an object with the keys being breakpoint values (`xs`, `sm`, etc...) and the value being a number for how wide the input should (1-12) where the rest of the value is given to the label.
It doesn't seem like it is documented. Plus looking at the bootstrap docs, they changed the form grid to use `placeholder` for labels in the examples.

https://stackblitz.com/edit/reactstrap-validation-v2-grnaax?file=Example.js

**Comment by Trancedified** [comment]
Thank you all for the feedback. This issue has been resolved.
