### ISSUE TITLE
Img in radio label

### ISSUE THREAD

**Issue by Shyghar** [Availity/availity-reactstrap-validation#148]
Hi, 
is there a way to insert dinamic backgound to a radio input label? 

```
const pStyle = { background-image: 'url("/content/images/'+el.nome + '.jpg")'  };
return (<AvRadio style={pStyle} value={el.nome} />)
```

With this code the background will go on the input and not on the label.
Is there a way to move it?

**Comment by GoPro16** [comment]
With the current `AvRadio` behavior we don't have a prop to spread `formGroupProps` onto the component. A prop would need to be added [here](https://github.com/Availity/availity-reactstrap-validation/blob/master/src/AvRadio.js#L80) in order to support this. Feel free to open a PR.

Otherwise you can create it using the `AvInput` and `FormGroup` components with some hack.
https://codesandbox.io/s/reactstrap-validation-issue-148-wl3o9

**Comment by GoPro16** [comment]
Going to close this, you can re-open if you have any further questions
