### ISSUE TITLE
Support for bootstrap v.4.0.0-beta

### ISSUE THREAD

**Issue by fantua** [Availity/availity-reactstrap-validation#35]
I'm trying using this lib with:
```json
"bootstrap": "4.0.0-beta",
"reactstrap": "^5.0.0-alpha.3"
```

But after releasing `bootstrap 4.0.0-beta` validation API was changed ([v.4-alpha](https://v4-alpha.getbootstrap.com/components/forms/#how-it-works) -> [v.4-beta](https://getbootstrap.com/docs/4.0/components/forms/#how-it-works)). Looks like `reactstrap` also update his API. 

Currently validation is broken.

**Comment by TheSharpieOne** [comment]
Not too sure if this library should interact with the DOM via `setCustomValidity` to trigger the CSS styles via pseudo-classes or just use the "server-side" classes.

Thoughts?

**Comment by jsarman** [comment]
Also Testing with latest reactstrap, and can confirm that validation is failing, also failed with latest moment 2.19.0, so I had to explicitly set moment to 2.18.1. The moment issue is documented at https://github.com/moment/moment/issues/4216

**Comment by fantua** [comment]
@TheSharpieOne just need to update `reactstrap` version to `reactstrap@next`. Latest version support `bootstrap 4.0.0-beta` as well.

**Comment by fantua** [comment]
Also need update `availity-reactstrap-validation` code to support new `reactstrap` components API.

**Comment by TheSharpieOne** [comment]
So... I looked into it and even made some changes but ran into some issues because reactstrap hasn't released https://github.com/reactstrap/reactstrap/pull/624 and (mostly) because bootstrap is having issues (https://github.com/twbs/bootstrap/issues/23426 in particular but there are others) I fear it might be too soon to make some changes.
I do want to give this project some attention and a complete refactor... but I probably will not have time until next month :(

I'll release what I have as `@next`, but just know some things are not going to work (mostly around checkboxes and radios)

**Comment by fantua** [comment]
> I'll release what I have as @next, but just know some things are not going to work (mostly around checkboxes and radios)

For now sounds great! Thank you.

**Comment by fantua** [comment]
@TheSharpieOne any updates on this?

**Comment by TheSharpieOne** [comment]
I pushed the next tag shortly after commenting. It should be on npm

**Comment by TheSharpieOne** [comment]
Closing as the v2.0.0-beta supports reactstrap 5.0.0-beta which supports bootstrap v4.0.0
