### ISSUE TITLE
Using custom checkbox style from external package. 

### ISSUE THREAD

**Issue by ArbanNichols** [Availity/availity-reactstrap-validation#40]
I'm having trouble rendering a custom checkbox styling from an external npm package called pretty-checkbox with the AvGroup tag.

**Comment by TheSharpieOne** [comment]
You can use `tag` on `AvInput` providing a custom/external component which is another input. Since your custom input has wrapping element, you need to pass the props to the raw input (removing any other props and using them where they best fit; if needed). For example, I added a `shape` and `color` prop to allow you to customize the shape and color of the PrettyCheckbox whenever you use it. You can add more to allow better customization of the various variations of PrettyCheckbox.

AvPrettyCheckbox.js:
```jsx
import React from 'react';
import { AvInput } from 'availity-reactstrap-validation';

function PrettyCheckbox ({ className, shape = 'default', color, children, valid, ...props }) {
  // className contains the validation classes
  // shape and color are custom props passed through, you can use them as you which and add more.
  // children is handy for creating the label value.
  // valid is a boolean indicating if the input is currently valid or not.
  // props contains things like the event listeners (onChange, onBlur, etc) or other props, like the type. All of these need to go onto the raw <input> so the validation can tap into the value.
  return (
    <div className={`pretty ${className} p-${shape}`}>
      <input {...props} />
      <div className={`state${color ? ` p-${color}` : ''}`}>
        <label>{children}</label>
      </div>
    </div>
  );
}

export default function AvPrettyCheckbox (props) {
  return <AvInput {...props} tag={PrettyCheckbox} type="checkbox" />;
}
```

Usage:
After importing you custom component (`AvPrettyCheckbox` in this case), you can use it just as you would an `AvInput`. This means the same fields are required (`name`). Also, since this generates a checkbox, you can use the special checkbox value props (`trueValue` and `falseValue`) as documented: https://availity.github.io/availity-reactstrap-validation/components/checkboxes/ 
```jsx
import AvPrettyCheckbox from './AvPrettyCheckbox ';
// ...then, within an AvForm
<AvPrettyCheckbox name="checkIt" required>Check it out!</AvPrettyCheckbox>
```

Demo: https://www.webpackbin.com/bins/-Kxk-F3R8CLPJqnlY2Uh

**Comment by ArbanNichols** [comment]
Thanks! I have a lot to learn when it comes to react and javascript but this helps me trmendously.
