### ISSUE TITLE
class name for valid and invalid input

### ISSUE THREAD

**Issue by Fredo70** [Availity/availity-reactstrap-validation#66]
reactstrap set the class for a valid input to `is-valid` and `is-invalid` for an invalid input.
_availity_ set the class to `av-valid` respectively `av-invalid`.
Do I miss something?

**Comment by TheSharpieOne** [comment]
Just extra classes for you to target. Their is also av-touched and av-dirty. You can use these classes to style fields different via css based on their current validation state.

**Comment by Fredo70** [comment]
Ok. But why don't you set the reactstrap class?

**Comment by TheSharpieOne** [comment]
I switched most of the class names to be `is-{thing}` such as `is-dirty` and `is-touched` but I could not do `is-valid` and `is-invalid` as those trigger styles in default bootstrap which may not be wanted. This is mostly the `is-valid` as it is more rare to see the "success" validation styles in the wild. `av-valid` and `av-invalid` are still used in case custom styles want to target those and `is-invalid` is used when when invalid (along with `av-invalid`).
Yes, it's slightly opinionated, only `is-invalid` and not `is-valid`, but it is more common, and this is **availity** reactstrap validation and that is the styles for Availity.
Closing since it isn't an issue, but more of a question (which is hopefully answered). Feel free to keep the conversion going if you need to.
