### ISSUE TITLE
Trigger real form submit

### ISSUE THREAD

**Issue by Sathras** [Availity/availity-reactstrap-validation#69]
I understand that react thinking may not encourage page redirects, internal links and form submissions. However, creating a loginform with `http-only` cookies, i do require a "real" form.

Is there a way to trigger the real form submit within the handleValidSubmit() method? E.g.:
```javascript
// React Class
  handleValidSubmit(e, values) {
    this.form.submit()
  }

  render(){
    [...]
      const {error} = this.state;
      const {onValidSubmit, onInvalidSubmit} = this;
      return(
        <AvForm
          acceptCharset="UTF-8"
          action="/destination"
          className = {error ? 'was-validated' : 'needs-validation'}
          method="post"
          onValidSubmit={handleValidSubmit}
          onInvalidSubmit={handleInvalidSubmit}
          ref = {r => this.form = r}
        >
    [...]
    );
  }
```
Thanks!

Edit: I managed via id and document.getElementById() but a ref solution would be preferable

**Comment by TheSharpieOne** [comment]
`http-only` cookies still get sent with AJAX request, the `http-only` just means your code cannot access the value.
You cannot trigger a "real" form submission to navigate the user because this library uses the "real" form submission to trigger the validation logic. In your handleValidSubmit, you can have a plain form be populated with the data and submitted.

**Comment by Sathras** [comment]
Thanks a lot! That is awesome to know! Ill experiment a little further
