### ISSUE TITLE
Availity date picker not working in IE browser.

### ISSUE THREAD

**Issue by AlpeshMN** [Availity/availity-reactstrap-validation#87]
Hi @TheSharpieOne , Hope you are doing well.

I am using availity date picker components for my react project. Date picker is not working for IE browser instead it works as a textfield. And when i submit the form from IE, it gives me undefined values of it. Below are the date picker fields i am using first with **AvField** and second with **AvInput**. On chrome, "/" is auto populated while in IE it's not instead i have to enter "/" manually which cause the issue while getting value of that field.

When i enter date manually in IE, it gives me value like below.
<img width="364" alt="screen shot 2018-07-31 at 5 23 31 pm" src="https://user-images.githubusercontent.com/37811280/43488105-a012ec64-94e6-11e8-90a4-a084a7144bb8.png">

`<Col xs="3" sm="3">
                <AvField type='date' name='medDob' value={dashboardDataval.data.member.dateOfBirth} onChange={this.getMedicaidValues} label='Date of Birth*' validate={{
                  max: {value: currentDate, errorMessage: 'Date should not be in future!'},
                  required: {value: true, errorMessage: 'Date of Birth is required!'},
                  date: {format: 'MM/DD/YYYY', errorMessage: 'Date format should be MM/DD/YYYY!'}
                }}
                />
              </Col>
              <Col xs="3" sm="3">
                <AvGroup>
                  <Label for='date'>Date of Birth*</Label>
                  <AvInput name='medDob' id='date' type={'date'} value={dashboardDataval.data.medicaidMember.dateOfBirth} onChange={this.getMedicaidValues} placeholder='mm/dd/yyyy' max={currentDate} required/>
                  <AvFeedback>Date is required and must not be in future!</AvFeedback>
                </AvGroup>
              </Col>`

**Comment by TheSharpieOne** [comment]
I believe the issue is with your `onChange` method. Since it was not provided, I simply removed `onChange` and `value` so that I could run the code you provided. I was not able to replicate the issue in IE.
https://stackblitz.com/edit/reactstrap-validation-v2-qhgkrp?file=Example.js
![date-validation-ie](https://user-images.githubusercontent.com/664714/43534941-a07c0c9e-9586-11e8-8f49-0adce76f7975.gif)

If you can, please provide your `onChange` method so I can better understand what is happening.

**Comment by AlpeshMN** [comment]
Hi Evan,

Thanks for your valuable reply. onChange function i am actually formating date to "mm/dd/yyyy" with below function. 

```
`<AvField
    type='date'
    name='medDob'
    onChange={this.getMedicaidValues}
    label='Date of Birth*'
    validate={{
       max: {value: currentDate, errorMessage: 'Date should not be in future!'},
       required: {value: true, errorMessage: 'Date of Birth is required!'},
       date: {format: 'MM/DD/YYYY', errorMessage: 'Date format should be MM/DD/YYYY!'}
     }}
  />`
```

```
`getMedicaidValues(event){
    prformStore.setMedicaidValues(event.target);
  }`

```
```
@action setMedicaidValues(val) {
   this.medicaidMember.dateOfBirth = this.changeDateFormat(val.value);
 }
```

```
@action changeDateFormat(date){
      let getDate;
      if (date){
        getDate = date.split('-');
        return getDate[1] + '/' + getDate[2] + '/' + getDate[0];
      }
    }
```

That's were it's stopped working on IE. I just realized that in Chrome when we submit date it's going as "yyyy-mm-dd" and on IE it's format is "mm/dd/yyyy".

What should i do in order to get date formatted in "mm/dd/yyyy" only?

**Comment by TheSharpieOne** [comment]
Since IE doesn't support the input type of "date" it doesn't adhere to the spec which says that the value of a date input should be in the ISO standard, which is "yyyy-mm-dd" when the field is valid or `undefined` when it is not. This means for browsers which support the date input type, you will either get a date in "yyyy-mm-dd" or `undefined`; you will **never** get a partial date input.

For browsers which do not support the date input type, you get whatever the field has in it (knowing that the validation library will validate the input and ensure it is valid and in the right format for the onSubmit/onValidSubmit/onInvalidSubmit calls backs)

So, for IE you **will** get partial date input values. You're code should handle that.

```javascript
@action changeDateFormat(date){
  if (date && (/^\d{4}-\d\d-\d\d$/.test(date) || /^\d\d\/\d\d\/\d{4}$/.test(date))){
    // if it's a valid date
    if(data.indexOf('-') > -1) {
      // it's in yyyy-mm-dd format
      const [year, month, day] = date.split('-');
      return `${month}/${day}/${year}`;
    }
    // else it should already by in mm/dd/yyyy format
    return data;
  }
  // else it's not a valid date... not sure what you want to do.
}
```

**Comment by AlpeshMN** [comment]
Thanks @TheSharpieOne ,
below one worked for me.

` @action changeDateFormat(date){
      if (date && (/^\d{4}-\d\d-\d\d$/.test(date))){
        // if it's a valid date
        if (date.indexOf('-')) {
          // it's in yyyy-mm-dd format
          const [year, month, day] = date.split('-');
          return `${month}/${day}/${year}`;
        }
      } else {
        if (date.indexOf('/')) {
          // it's in mm-dd-yyyy format
          const [month, day, year] = date.split('/');
          return `${month}/${day}/${year}`;
        }
      }
    }`
